In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sn
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
import graphviz
import scipy
from math import sqrt

#estimators
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn import linear_model

#model metrics
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

In [2]:
#Models
modelSVR = SVR()
modelRF = RandomForestRegressor()
modelLR = LinearRegression()
modelRFC = RandomForestClassifier()

In [3]:
creditxxx = pd.read_csv('c:/users/sully/desktop/C5 T1/creditxxx.csv')
creditxxx.head()

Unnamed: 0  ID  LIMIT_BAL  SEX  MARRIAGE  AGE  default_payment_next_month  \
0           0   1      20000    2         1   24                           1   
1           1   2     120000    2         2   26                           1   
2           2   3      90000    2         2   34                           0   
3           3   4      50000    2         1   37                           0   
4           4   5      50000    1         1   57                           0   

   Pay_code_avg      Bill_avg  Pay_avg  ...  Bill_avg_quint  Pay_avg_quint  \
0     -0.333333   1284.000000      0.0  ...               0              0   
1      0.500000   2846.166667      0.0  ...               0              0   
2      0.000000  16942.166667   1518.0  ...               2              1   
3      0.000000  38555.666667   2000.0  ...               3              2   
4     -0.333333  18223.166667   2000.0  ...               2              2   

   lim_bal_quint  EDUCATION_0  EDUCATION_1  EDUCATION_2  EDUCATION_3  \
0              0            0            0            1            0   
1              2            0            0            1            0   
2              1            0            0            1            0   
3              0            0            0            1            0   
4              0            0            0            1            0   

   EDUCATION_4  EDUCATION_5  EDUCATION_6  
0            0            0            0  
1            0            0            0  
2            0            0            0  
3            0            0            0  
4            0            0            0  

[5 rows x 21 columns]

In [4]:
creditx = pd.read_csv('c:/users/sully/desktop/C5 T1/default of credit card clients.csv', skiprows=1)
creditx.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...          0          0          0         0       689         0   
1  ...       3272       3455       3261         0      1000      1000   
2  ...      14331      14948      15549      1518      1500      1000   
3  ...      28314      28959      29547      2000      2019      1200   
4  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0                           1  
1      1000         0      2000                           1  
2      1000      1000      5000                           0  
3      1100      1069      1000                           0  
4      9000       689       679                           0  

[5 rows x 25 columns]

In [4]:
X = creditxxx.iloc[:,1:21]

In [5]:
X.head()

ID  LIMIT_BAL  SEX  MARRIAGE  AGE  default_payment_next_month  \
0   1      20000    2         1   24                           1   
1   2     120000    2         2   26                           1   
2   3      90000    2         2   34                           0   
3   4      50000    2         1   37                           0   
4   5      50000    1         1   57                           0   

   Pay_code_avg      Bill_avg  Pay_avg  Pay_code_quint  Bill_avg_quint  \
0     -0.333333   1284.000000      0.0               1               0   
1      0.500000   2846.166667      0.0               4               0   
2      0.000000  16942.166667   1518.0               2               2   
3      0.000000  38555.666667   2000.0               2               3   
4     -0.333333  18223.166667   2000.0               1               2   

   Pay_avg_quint  lim_bal_quint  EDUCATION_0  EDUCATION_1  EDUCATION_2  \
0              0              0            0            0            1   
1              0              2            0            0            1   
2              1              1            0            0            1   
3              2              0            0            0            1   
4              2              0            0            0            1   

   EDUCATION_3  EDUCATION_4  EDUCATION_5  EDUCATION_6  
0            0            0            0            0  
1            0            0            0            0  
2            0            0            0            0  
3            0            0            0            0  
4            0            0            0            0

In [49]:
X = X.drop(labels='default_payment_next_month', axis=1)
X = X.drop(labels='lim_bal_quint',axis=1)
X = X.drop(labels='Pay_code_quint', axis=1)
X = X.drop(labels='Bill_avg_quint', axis=1)
X = X.drop(labels='Pay_avg_quint', axis=1)

In [50]:
X = X.drop(labels='SEX', axis=1)
X = X.drop(labels='MARRIAGE', axis=1)
X = X.drop(labels='ID', axis=1)
X = X.drop(labels='EDUCATION_6', axis=1)

In [83]:
X_scaled = preprocessing.scale(X)
X2 = pd.DataFrame(X_scaled)

In [84]:
X2.head()

0         1         2         3         4         5         6  \
0 -1.136720 -1.246020 -0.153635 -0.690692 -0.341942 -0.021608 -0.738375   
1 -0.365981 -1.029047  0.694835 -0.665997 -0.341942 -0.021608 -0.738375   
2 -0.597202 -0.161156  0.185753 -0.443170 -0.250292 -0.021608 -0.738375   
3 -0.905498  0.164303  0.185753 -0.101507 -0.221191 -0.021608 -0.738375   
4 -0.905498  2.334029 -0.153635 -0.422920 -0.221191 -0.021608 -0.738375   

        7         8         9        10  
0  1.0669 -0.442752 -0.064163 -0.097063  
1  1.0669 -0.442752 -0.064163 -0.097063  
2  1.0669 -0.442752 -0.064163 -0.097063  
3  1.0669 -0.442752 -0.064163 -0.097063  
4  1.0669 -0.442752 -0.064163 -0.097063

In [87]:
y = creditxxx.iloc[:,6:7]

In [88]:
y.head()

default_payment_next_month
0                           1
1                           1
2                           0
3                           0
4                           0

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X2, y, test_size=0.25, random_state=997)

In [90]:
y_test.head()

default_payment_next_month
3325                            1
13661                           0
22655                           0
12788                           0
17937                           0

In [91]:
X_test.head()

0         1         2         3         4         5         6  \
3325  -0.211833 -0.812074  0.185753  1.528070  0.056537 -0.021608  1.354326   
13661  2.562830  0.272789  0.185753  0.075043 -0.040064 -0.021608  1.354326   
22655  1.792091  0.381275 -0.323329 -0.427926 -0.340070 -0.021608 -0.738375   
12788  0.096463  1.140680 -0.832412 -0.172268 -0.160815 -0.021608  1.354326   
17937 -0.674276 -0.052670  0.016059  0.223635  0.865569 -0.021608  1.354326   

              7         8         9        10  
3325  -0.937295 -0.442752 -0.064163 -0.097063  
13661 -0.937295 -0.442752 -0.064163 -0.097063  
22655  1.066900 -0.442752 -0.064163 -0.097063  
12788 -0.937295 -0.442752 -0.064163 -0.097063  
17937 -0.937295 -0.442752 -0.064163 -0.097063

In [108]:
modelRFC.fit(X_train, np.ravel(y_train))

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [109]:
modelRF.fit(X_train, np.ravel(y_train))

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [110]:
modelSVR.fit(X_train, np.ravel(y_train))

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [111]:
modelLR.fit(X_train, np.ravel(y_train))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [112]:
from sklearn.model_selection import cross_val_score

In [116]:
print(cross_val_score(modelRFC, X_train, np.ravel(y_train))) 

[0.79977778 0.79488889 0.79644444 0.79444444 0.79977778]


In [117]:
print(cross_val_score(modelRF, X_train, np.ravel(y_train))) 

[0.1097073  0.09570217 0.13336809 0.10451302 0.11916737]


In [118]:
print(cross_val_score(modelLR, X_train, np.ravel(y_train))) 

[0.09275629 0.08766077 0.09402966 0.08695408 0.08783891]


In [119]:
print(cross_val_score(modelSVR, X_train, np.ravel(y_train))) 

[0.09691967 0.09316618 0.10239782 0.07915993 0.09363071]


In [120]:
y_pred = modelRFC.predict(X_test)

In [121]:
print('Mean Squared Error:', mean_squared_error(y_test, y_pred))  
print('R-Sq:', r2_score(y_test, y_pred)) 
print('Root Mean Squared Error:', np.sqrt(mean_squared_error(y_test, y_pred)))

Mean Squared Error: 0.20733333333333334
R-Sq: -0.17598669947698986
Root Mean Squared Error: 0.4553387017741116


In [122]:
modelRFC.score(X_train,y_train)

0.9983111111111111

In [123]:
modelRF.score(X_train,y_train)

0.8727582962167469

In [124]:
modelSVR.score(X_train,y_train)

0.10401192052440167

In [125]:
modelLR.score(X_train,y_train)

0.09088246157735946

In [126]:
predictions = modelRFC.predict(X_test)

In [127]:
predRsquared = r2_score(y_test,predictions)

In [128]:
print('R Squared: %.3f' % predRsquared)

R Squared: -0.176
